name: PhpFs CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: fileinfo
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: composer test
